### PR TITLE
Basic HA kubernetes deployment

### PR DESCRIPTION
**Pull request by mark-burnett**
This replaces the bootkube-based approach with a less elegant, but more resilient approach.

A fully constructed cluster (there is no way to replace a genesis node with a normal master node yet) should have the following resiliency properties:

- functioning during a single-node reboot
- regaining full functionality after multi-node or full cluster reboots
- maintaining functionality during node loss

It currently has the following **mis**features:

- genesis script blocks until the master etcd cluster is completely configured & joined
  - genesis node will be fully functioning as a single node cluster during this time
  - you must initiate the join of all other master nodes before this script can end
- transitioning from 1 etcd node to 2 causes a temporary outage of the kubernetes control plane
- uses flannel instead of calico, so no advanced security policies are available
- does not allow flexible key/cert management (you must provide a ca cert + key and a pub/priv key for service accounts)
- does not have a helm/armada deployment stage, only has static manifests and simple `kubectl apply`
- does not support http(s) proxies

Notes:

- an image matching this code is pushed to `quay.io/attcomdev/promenade:experimental`
- `export KUBECONFIG=/etc/kubernetes/admin/kubeconfig.yaml` will let you use `kubectl` normally on a master
- there are currently two different, but very similar shell scripts `genesis.sh` and `join.sh`

### CODE REVIEW

**Comment by aric49** [comment]
Mark, this looks fantastic.   Thanks for putting in such a great effort on getting this squared away.  If there aren't any objections, I think this is a good starting place from which we can build on.

**Comment by alanmeadows** [comment]
Mark,

A few quick questions:

_genesis script blocks until the master etcd cluster is completely configured & joined_

Would it be possible to split the launch and the "polling" to two separate processes so potentially two different things could run them or that is complex at this time?

_transitioning from 1 etcd node to 2 causes a temporary outage of the kubernetes control plane_

Does that mean until you deploy 2 or 3 masters which would house etcd, the cluster should not be targeted for any application installs? Trying to determine the impact of "outage"

_uses flannel instead of calico, so no advanced security policies are available_

Would we be able to achieve calico (with resilient etcd backend) by next week or this is going to take longer?

_does not allow flexible key/cert management (you must provide a ca cert + key and a pub/priv key for service accounts)_

Would we be able to achieve certificate generation (if not supplied) by next week, or as a stub, a simple utility to generate the generated input this expects

_does not have a helm/armada deployment stage, only has static manifests and simple kubectl apply_

Is that targeted for next week?

_does not support http(s) proxies_

Is this targeted for next week?

Trying to gauge what we're determining won't fit in the timeline versus what is included in this commit.

**Comment by mark-burnett** [comment]
Re: your questions:

>> genesis script blocks until the master etcd cluster is completely configured & joined

> Would it be possible to split the launch and the "polling" to two separate processes so potentially two different things could run them or that is complex at this time?

>> transitioning from 1 etcd node to 2 causes a temporary outage of the kubernetes control plane

> Does that mean until you deploy 2 or 3 masters which would house etcd, the cluster should not be targeted for any application installs? Trying to determine the impact of "outage"

My plan for addressing these two issues is to have genesis start with 3 etcd instances with a background process that is monitoring for the masters to all join.  Once they join, it will remove the 2 auxiliary etcd members, delete their manifests and then delete its own manifest.

This also addresses a race condition which @gardlt exposed in the join order of the master nodes.

It is currently possible to deploy things without adding more nodes beyond genesis.  The outage only occurs once a node has joined and entered ready status.  Then there is a period where the new etcd node has been added to the existing node, but its kubelet has backed off restarting it (because it has  failed to join the cluster a few times at that point).

>> uses flannel instead of calico, so no advanced security policies are available

> Would we be able to achieve calico (with resilient etcd backend) by next week or this is going to take longer?

I believe that even though calico speaks etcd v2, we can use the same etcd instance, because etcd v3 actually speaks both versions of the protocol.  That should make resilient etcd no problem (even if this fails, we can just repeat the same pattern).

I think getting this done will be quicker if certs + keys are 100% provided up front instead of partially generated.  Are you OK with 100% up front cert generation (via a script)?  If not, it's OK, I will still push on this as it is obviously still possible.

>> does not allow flexible key/cert management (you must provide a ca cert + key and a pub/priv key for service accounts)

> Would we be able to achieve certificate generation (if not supplied) by next week, or as a stub, a simple utility to generate the generated input this expects

Happy to add a script to generate these.  The thing I'm trying to avoid is getting data off of genesis and putting it on other nodes.  I'd rather just push from the top to everywhere for now.  Once we have drydock provisioning joining nodes, then we have a clear path for putting data on the nodes.

I asked above, but it's probably more clear here.  Is it OK to fully generate all certs/keys up front and pass them in?  This simplifies a few things, because now we can just template those data into, e.g. kubernetes secrets & configmaps for calico.

>> does not have a helm/armada deployment stage, only has static manifests and simple kubectl apply

> Is that targeted for next week?

Yes, definitely a priority.

>> does not support http(s) proxies

> Is this targeted for next week?

Yes.  I think Aric is taking this on and already has a start.

**Comment by mark-burnett** [comment]
@alanmeadows forgot to mention you in the above comment. ^

**Comment by alanmeadows** [comment]
@mark-burnett All responses make sense to me.  

Fine to generate cert/keys up front and feed them in -- main goal is they are not baked in code and checked into github.

**Pull request merged**
