### PR TITLE
Add apiVersion and kind to config

### PR DESCRIPTION
**Pull request by mark-burnett**
This will be a step forward for integration with drydock.

### CODE REVIEW

**Comment by sh8121att** [comment]
This layout is fine, however we used the below in the Drydock YAML docs

```
apiVersion: xxx
kind: xxx
metadata:
  a: xxx
  b: xxx
spec:
  actual_data: xxx
```

**Review by sh8121att — COMMENTED** [review]
This layout is fine, however we used the below in the Drydock YAML docs

```
apiVersion: xxx
kind: xxx
metadata:
  a: xxx
  b: xxx
spec:
  actual_data: xxx
```

**Comment by v1k0d3n** [comment]
@sh8121att's right. a similar format would be really nice. both appear to borrow API logic from kubernetes which was obtained from the [Kubernetes API Reference Docs](https://kubernetes.io/docs/api-reference/v1.6/).

**Comment by mark-burnett** [comment]
Superceded by #11

**Pull request closed without merging**
